version: '3.3'

services:
  wordpress:
    build:
       context: '.docker'
       dockerfile: Dockerfile
    container_name: ${APP_NAME}_wordpress
    depends_on:
      - mysql
      - mailhog
    links:
      - mysql:mysql
      - mailhog
    tty: true
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX}
    networks:
      - wordpress-local
    volumes:
      - ./.docker/nginx/.htaccess:/var/www/html/.htaccess
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini 
      - ../wp-app:/var/www/html

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wordpress
    links:
      - wordpress
      - phpmyadmin
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/certs/:/etc/nginx/certs
      - /var/log/nginx:/var/log/nginx
    networks:
      wordpress-local:
        aliases:
          - wp-api

  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - wordpress-local
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    networks:
      - wordpress-local

  mailhog:
    container_name: ${APP_NAME}_mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - wordpress-local

volumes:
  mysql_data:
    driver: local
networks:
  wordpress-local:
    external: true
